### ISSUE TITLE
Provider keeps crashing when creating a role

### ISSUE THREAD

**Issue by clement-chaneching** [onelogin/terraform-provider-onelogin#126]
Hello,

I m trying to add my user as admin to my app:
resource "onelogin_roles" "vision_demo"{
    name = "visionadmin"
    apps = [123]
    admins= [123] (also tried with users = [123]
}

```
Stack trace from the terraform-provider-onelogin_v0.4.9 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 114 [running]:
github.com/dikhan/terraform-provider-openapi/v3/openapi.resourceFactory.validateImmutableProperty({{0xff3050, 0xc000754380}, 0x8bb2c97000, 0x12a05f200, 0x2540be400, 0x3b9aca00}, 0xc0019b3200, {0x0?, 0x0?}, {0x0, ...}, ...)
github.com/dikhan/terraform-provider-openapi/v3@v3.0.0/openapi/resource_factory.go:480 +0x898
github.com/dikhan/terraform-provider-openapi/v3/openapi.resourceFactory.checkImmutableFields({{0xff3050, 0xc000754380}, 0x8bb2c97000, 0x12a05f200, 0x2540be400, 0x3b9aca00}, 0xc00126d700, {0x7ff9ef3eb488, 0xc0002484d0}, {0x15e9d08, ...})
github.com/dikhan/terraform-provider-openapi/v3@v3.0.0/openapi/resource_factory.go:432 +0x327
github.com/dikhan/terraform-provider-openapi/v3/openapi.resourceFactory.update({{0xff3050, 0xc000754380}, 0x8bb2c97000, 0x12a05f200, 0x2540be400, 0x3b9aca00}, 0xc00126d700, {0xe28bc0?, 0xc0002484d0})
github.com/dikhan/terraform-provider-openapi/v3@v3.0.0/openapi/resource_factory.go:223 +0x273
github.com/dikhan/terraform-provider-openapi/v3/openapi.crudWithContext.func1.1()
github.com/dikhan/terraform-provider-openapi/v3@v3.0.0/openapi/common.go:21 +0x36
created by github.com/dikhan/terraform-provider-openapi/v3/openapi.crudWithContext.func1
github.com/dikhan/terraform-provider-openapi/v3@v3.0.0/openapi/common.go:21 +0x13e

Error: The terraform-provider-onelogin_v0.4.9 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

I saw similar error happened previously but it just says it should have been fixed releases ago...
Any idea or improvement to get a proper error msg?

Any improvement to the doc would also be welcome since I then need to figure out how to generate a client ID and secret for my OIDC app, and the doc really isnt helping me.

Thanks for the help
Clement

**Comment by clement-chaneching** [comment]
Actually what I want is add my account as Application admin, which is a "privilege" in OneLogin.
But there is no terraform to assign privileges to roles it seems in the Terraform provider:
`POST https://<subdomain>/api/1/privileges/:id/roles
`

Is it possible to do it?

**Comment by clement-chaneching** [comment]
Nevermind I just understood that the plugin crashes when it tries to update something, so we have to replace everytime
